version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false
services:
  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - db
    ports:
      - 2368-2370:2368
    environment:
      url: http://blog.suryad.com
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: goodpass
      database__connection__database: ghost
    labels:
      - traefik.backend=ghost
      - traefik.frontend.rule=Host:blog.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=2368
    networks:
      - internal
      - proxy
    volumes:
      - /opt/ghost_content:/var/lib/ghost/content
    deploy:
      replicas: 3

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: goodpass
    labels:
      - traefik.enable=false
    networks:
      - internal
    volumes:
      - /opt/ghost_mysql:/var/lib/mysql

  suryadcom:
    image: dantuluri/suryadcom:latest
    restart: always
    labels:
      - traefik.backend=suryadcom
      - traefik.frontend.rule=Host:suryad.com
      - traefik.docker.network=proxy
      - traefik.port=5000
    networks:
      - proxy
    deploy:
      replicas: 2
  sd1suryadcom:
    image: dantuluri/sd1:latest
    restart: always
    labels:
      - traefik.backend=sd1suryadcom
      - traefik.frontend.rule=Host:sd1.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=5001
    networks:
      - proxy
    deploy:
      replicas: 2
  stats:
    image: usefathom/fathom:latest
    volumes:
      - /host/fathom/stats.db:/app/fathom.db
    networks:
      - proxy
    labels:
      - traefik.backend=stats
      - traefik.frontend.rule=Host:stats.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=8080
    ports:
      - 8081:8080
  statblog:
    image: usefathom/fathom:latest
    volumes:
      - /host/fathom/statblog.db:/app/fathom.db
    networks:
      - proxy
    labels:
      - traefik.backend=statblog
      - traefik.frontend.rule=Host:statblog.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=8080
    ports:
      - 8082:8080
  statmain:
    image: usefathom/fathom:latest
    volumes:
      - /host/fathom/statmain.db:/app/fathom.db
    networks:
      - proxy
    labels:
      - traefik.backend=statmain
      - traefik.frontend.rule=Host:statmain.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=8080
    ports:
      - 8083:8080
  statdata:
    image: usefathom/fathom:latest
    volumes:
      - /host/fathom/statdata.db:/app/fathom.db
    networks:
      - proxy
    labels:
      - traefik.backend=statdata
      - traefik.frontend.rule=Host:statdata.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=8080
    ports:
      - 8084:8080
  statsd:
    image: usefathom/fathom:latest
    volumes:
      - /host/fathom/statsd.db:/app/fathom.db
    networks:
      - proxy
    labels:
      - traefik.backend=statsd
      - traefik.frontend.rule=Host:statsd.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=8080
    ports:
      - 8085:8080

