version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false
services:
  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - db
    ports:
      - 2368-2370:2368
    environment:
      url: http://blog.suryad.com
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: goodpass
      database__connection__database: ghost
    labels:
      - traefik.backend=ghost
      - traefik.frontend.rule=Host:blog.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=2368
    networks:
      - internal
      - proxy
    volumes:
      - /opt/ghost_content:/var/lib/ghost/content
    deploy:
      replicas: 3

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: goodpass
    labels:
      - traefik.enable=false
    networks:
      - internal
    volumes:
      - /opt/ghost_mysql:/var/lib/mysql

  suryadcom:
    image: dantuluri/suryadcom:latest
    restart: always
    labels:
      - traefik.backend=suryadcom
      - traefik.frontend.rule=Host:suryad.com
      - traefik.docker.network=proxy
      - traefik.port=5000
    networks:
      - proxy
    deploy:
      replicas: 2
  sd1suryadcom:
    image: dantuluri/sd1:latest
    restart: always
    labels:
      - traefik.backend=sd1suryadcom
      - traefik.frontend.rule=Host:sd1.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=5001
    networks:
      - proxy
    deploy:
      replicas: 2
  fathom:
    image: usefathom/fathom:latest
    volumes:
      - /host/fathom/fathom.db:/app/fathom.db
    networks:
      - proxy
    labels:
      - traefik.backend=fathom
      - traefik.frontend.rule=Host:stats.suryad.com
      - traefik.docker.network=proxy
      - traefik.port=8080
    ports:
      - 8080:8080

